### ISSUE TITLE
Nearby vessels shifting position after orbit edited to new body

### ISSUE THREAD

**Issue by DBooots** [Ezriilc/HyperEdit#6] opened 2016-03-08 18:25 UTC
Whenever I have two vessels in close proximity (~100m) and edit the orbit of one to another body, the position of the second changes. The change isn't reflected in the tracking station or map view until the second vessel is loaded when its position and orbit have suddenly changed.

Steps to reproduce:
Have 2 vessels in orbit within physics range (I had one in a 100km orbit of Minmus with the other 1s ahead)
Edit the orbit of one of them to another body (I changed the orbit of the leading vessel to a 100km orbit of Bop)
Return to tracking station, note that the orbit of the one that wasn't edited seems to be as it should be.
Select to fly that vessel and note that its orbit is no longer the same.

**Comment by khyperia** [comment] 2016-03-09 15:47
I couldn't reproduce this. I started a new save file, teleported one capsule to 100,000 orbit, another to 100,010 (so they're very close to each other), teleported the higher one to the same altitude at Bop, then teleported back, and the other capsule was at exactly the same place as it was before.

**Comment by DBooots** [comment] 2016-03-09 22:57
Weird. I removed all other mods except for HyperEdit, ModuleManager, Kerbal Engineer, and Toolbar with no change in behaviour. I am using KSP 1.0.4, though. Here's some screenshots of the sequence of events:
![Before teleporting](https://cloud.githubusercontent.com/assets/17708375/13653392/7d2d0e6e-e61f-11e5-99bc-011df400b5d9.png)
Before teleporting, one vessel leading the other by 1s in a 100km orbit of Minmus.
![Tracking station view](https://cloud.githubusercontent.com/assets/17708375/13653393/7d3174c2-e61f-11e5-80db-65ca8337defc.png)
Tracking station view of the vessel in Minmus orbit.
![Orbit changed](https://cloud.githubusercontent.com/assets/17708375/13653391/7d27c0ee-e61f-11e5-99c7-1d7a197e6cfe.png)
After selecting 'Fly' for the vessel in Minmus orbit. Note the changed Ap and Pe.
![GameData](https://cloud.githubusercontent.com/assets/17708375/13653394/7d38c18c-e61f-11e5-95ea-247cd5e8cec8.png)
GameData Directory

**Comment by Ezriilc** [comment] 2016-07-14 21:07
Has this issue been corrected with the recent release(s)?

**Comment by Ezriilc** [comment] 2016-07-20 15:50
I am unable to reproduce this in KSP 1.1.3, so I'm closing it.

**Closed by Ezriilc** 2016-07-20 15:50 UTC
